# Exemple de configuration IziProxy

# Configuration des environnements
environments:
  local:
    proxy_url: "http://proxy.example.com:8080"
    requires_auth: true
    auth_type: "ntlm"                     # Authentification NTLM en local (poste Windows)

  dev:
    proxy_url: "http://dev-proxy.example.com:8080"
    requires_auth: true
    auth_type: "basic"                    # Authentification basique

  prod:
    proxy_url: "http://prod-proxy.example.com:8080"
    requires_auth: false

# Configuration de la détection d'environnement
environment_detection:
  method: "auto"  # auto, env_var, hostname, ip, ask
  
  # Patterns pour la détection par nom d'hôte
  hostname_patterns:
    local: ["local", "laptop", "desktop", "dev-pc"]
    dev: ["dev", "staging", "test", "preprod"]
    prod: ["prod", "production"]
  
  # Expressions régulières pour la détection par nom d'hôte
  hostname_regex:
    local: ["^laptop-\\w+$", "^pc-\\w+$", "^desktop-\\w+$"]
    dev: ["^dev\\d*-", "^staging\\d*-", "^test\\d*-"]
    prod: ["^prod\\d*-", "^production\\d*-"]
  
  # Plages IP pour la détection par adresse IP
  ip_ranges:
    local: ["192.168.0.0/24", "127.0.0.1-127.0.0.255"]
    dev: ["10.0.0.0/16"]
    prod: ["172.16.0.0/16"]

# Configuration de la détection de proxy système
system_proxy:
  use_system_proxy: true  # Utiliser le proxy système si pas de proxy explicite
  detect_pac: true  # Détecter et utiliser les fichiers PAC
